// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::{DateTime, Utc};
use derive_builder::WebApiGen;
use diesel::prelude::*;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use crate::domain::eth_addr::EthAddr;


use crate::db_models::dex_gram::* ;
use crate::db_models::dex_gram_new::*;
use crate::schema::block_sync::dsl as block_sync_dsl;
use crate::schema::token_pairs::dsl as token_pairs_dsl;
use crate::schema::wallet_token_trades::dsl as wallet_token_trades_dsl;
use crate::schema::wallet_tokens::dsl as wallet_tokens_dsl;
use crate::schema::wallet_transactions::dsl as wallet_transactions_dsl;
use crate::schema::wallets::dsl as wallets_dsl;
